// All page copy, EN + ES. Spanish is conversational Mexican Spanish, not literal translation.

export const nav = {
  en: [
    { href: '/en', label: 'Home' },
    { href: '/en/buy/first-time-buyers', label: 'First-time buyers' },
    { href: '/en/rgv', label: 'Explore the RGV' },
    { href: 'https://www.aregtx.com/home_value', label: "What's my home worth?" },
    { href: '/en/reviews', label: 'Reviews' },
    { href: '/en/resources', label: 'Resources' },
    { href: '/en/about', label: 'About' },
  ],
  es: [
    { href: '/es', label: 'Inicio' },
    { href: '/es/buy/first-time-buyers', label: 'Primer hogar' },
    { href: '/es/rgv', label: 'Conoce el Valle' },
    { href: 'https://www.aregtx.com/home_value', label: '¿Cuánto vale mi casa?' },
    { href: '/es/reviews', label: 'Reseñas' },
    { href: '/es/resources', label: 'Recursos' },
    { href: '/es/about', label: 'Nosotros' },
  ],
};

export const ui = {
  en: { search: 'Search listings', menu: 'Menu', close: 'Close', lang: 'Español', viewArea: 'View area', photoComing: 'Photo coming' },
  es: { search: 'Ver propiedades', menu: 'Menú', close: 'Cerrar', lang: 'English', viewArea: 'Ver zona', photoComing: 'Foto próximamente' },
};

export const footer = {
  en: {
    tagline: 'Where your next chapter begins.',
    brokerLine: 'The Arper Group is a team operating under Alliance Real Estate Group.',
    trec: 'Texas law requires all license holders to provide the following to consumers:',
    iab: 'Information About Brokerage Services',
    cpn: 'TREC Consumer Protection Notice',
    rights: 'All rights reserved.',
    followUs: 'Follow along',
  },
  es: {
    tagline: 'Donde empieza tu próximo capítulo.',
    brokerLine: 'The Arper Group es un equipo que opera bajo Alliance Real Estate Group.',
    trec: 'La ley de Texas exige que todo agente con licencia entregue lo siguiente al consumidor:',
    iab: 'Información sobre servicios de corretaje',
    cpn: 'Aviso de protección al consumidor de TREC',
    rights: 'Todos los derechos reservados.',
    followUs: 'Síguenos',
  },
};

export const home = {
  en: {
    metaTitle: 'The Arper Group — Real estate in the Rio Grande Valley, made easier',
    metaDesc: 'A bilingual McAllen real estate team helping buyers, sellers and investors across the RGV. Every listing, every ZIP code — with advice you can trust.',
    heroEyebrow: 'Rio Grande Valley real estate',
    heroAlt: 'A modern Rio Grande Valley home',
    heroLine1: 'Any listing, any zip code.',
    heroLine2Pre: "RGV's ",
    heroLine2Accent: 'Real Estate',
    heroLine2Post: ' concierge.',
    heroBody: 'We help you discover the place where your story begins — not just a property, but a space that reflects your life and your next chapter.',
    ctaValue: "What's my home worth?",
    ctaFind: 'Find your space',
    missionLine: 'Real estate without the performance.',
    lensTitle: 'One team, two lenses',
    lensBody: 'You get both sides of every decision — the numbers and the potential.',
    lensMau: { name: 'Mauricio', role: 'The data', body: 'Market analysis, pricing strategy and marketing built as a system — not a post.' },
    lensPam: { name: 'Pamela', role: 'The potential', body: 'Design eye, future potential, and a search that actually stays enjoyable.' },
    teamCaption: 'Pamela & Mauricio · Arper',
    doorsTitle: 'Where are you headed?',
    doors: [
      { title: 'Buying', body: 'Start with a budget, not with Zillow. We represent you across the whole Valley.', href: '/en/buy/first-time-buyers', cta: 'For first-time buyers' },
      { title: 'Selling', body: 'A listing is a marketing campaign, not a database entry. Price from evidence, not ego.', href: 'https://www.aregtx.com/home_value', cta: "Get your home's value" },
      { title: 'Investing', body: 'The spreadsheet should survive the excitement. Coming soon to the site.', href: '/en/about', cta: 'Talk to us' },
    ],
    rgvTitlePre: 'Know the Valley ',
    rgvTitleAccent: 'before you buy',
    rgvBody: 'McAllen isn\u2019t Edinburg isn\u2019t Weslaco. Start with a neighborhood guide.',
    winsKicker: 'Recent wins',
    winsTitlePre: 'Keys ',
    winsTitleAccent: 'handed over',
    winsBody: 'Real families, real keys \u2014 a few of the Valley homes we\u2019ve closed lately.',
    soldTag: 'Sold',
    communitiesTitlePre: 'Homes in the Valley\u2019s ',
    communitiesTitleAccent: 'newest communities',
    communitiesBody: 'Master-planned parks, pools, and lakes \u2014 we know where the RGV is growing, and how to get you in early.',
    reviewQuote: 'Hands down the best real estate experience we\u2019ve ever had \u2014 he\u2019s in a league of their own.',
    reviewAttribution: 'Cesar G. \u00b7 Google review',
    closingTitle: 'Where your next chapter begins.',
    biling: 'Hablamos español. Y no traducimos palabra por palabra \u2014 te explicamos como se habla en el Valle.',
  },
  es: {
    metaTitle: 'The Arper Group — Bienes raíces en el Valle, más fácil',
    metaDesc: 'Equipo bilingüe de bienes raíces en McAllen para compradores, vendedores e inversionistas del Valle. Toda propiedad, todo código postal — con asesoría en la que puedes confiar.',
    heroEyebrow: 'Bienes raíces en el Valle de Texas',
    heroAlt: 'Una casa moderna del Valle de Texas',
    heroLine1: 'Cualquier propiedad, cualquier código postal.',
    heroLine2Pre: 'El concierge de ',
    heroLine2Accent: 'bienes raíces',
    heroLine2Post: ' del Valle.',
    heroBody: 'Te ayudamos a descubrir el lugar donde comienza tu historia — no solo una propiedad, sino un espacio que refleja tu vida y tu próximo capítulo.',
    ctaValue: '¿Cuánto vale mi casa?',
    ctaFind: 'Encuentra tu espacio',
    missionLine: 'Bienes raíces sin el show.',
    lensTitle: 'Un equipo, dos miradas',
    lensBody: 'Recibes los dos lados de cada decisión: los números y el potencial.',
    lensMau: { name: 'Mauricio', role: 'Los datos', body: 'Análisis de mercado, estrategia de precio y un marketing que es un sistema, no un post.' },
    lensPam: { name: 'Pamela', role: 'El potencial', body: 'Ojo para el diseño, el potencial de cada casa, y una búsqueda que sí se disfruta.' },
    teamCaption: 'Pamela & Mauricio · Arper',
    doorsTitle: '¿Para dónde vas?',
    doors: [
      { title: 'Comprar', body: 'Empieza con un presupuesto, no con Zillow. Te representamos en todo el Valle.', href: '/es/buy/first-time-buyers', cta: 'Para tu primer hogar' },
      { title: 'Vender', body: 'Un listado es una campaña, no un registro en el MLS. Precio con evidencia, no con ego.', href: 'https://www.aregtx.com/home_value', cta: 'Conoce el valor de tu casa' },
      { title: 'Invertir', body: 'El Excel debe sobrevivir a la emoción. Muy pronto en el sitio.', href: '/es/about', cta: 'Platícanos' },
    ],
    rgvTitlePre: 'Conoce el Valle ',
    rgvTitleAccent: 'antes de comprar',
    rgvBody: 'McAllen no es Edinburg, y no es Weslaco. Empieza con una guía de zona.',
    winsKicker: 'Cierres recientes',
    winsTitlePre: 'Llaves ',
    winsTitleAccent: 'entregadas',
    winsBody: 'Familias reales, llaves reales — algunas de las casas del Valle que hemos cerrado últimamente.',
    soldTag: 'Vendida',
    communitiesTitlePre: 'Casas en los ',
    communitiesTitleAccent: 'fraccionamientos más nuevos del Valle',
    communitiesBody: 'Parques, albercas y lagos con desarrollo planeado — sabemos hacia dónde crece el Valle, y cómo conseguirte un lugar temprano.',
    reviewQuote: 'Hands down the best real estate experience we\u2019ve ever had \u2014 he\u2019s in a league of their own.',
    reviewAttribution: 'Cesar G. \u00b7 Rese\u00f1a de Google',
    closingTitle: 'Donde empieza tu pr\u00f3ximo cap\u00edtulo.',
    biling: 'We speak English too \u2014 whichever language your family actually uses to make the decision.',
  },
};

export const rgvHub = {
  en: {
    metaTitle: 'Rio Grande Valley Real Estate & Neighborhoods | The Arper Group',
    metaDesc: 'Explore Rio Grande Valley real estate and neighborhoods \u2014 McAllen, Edinburg, Mission, Pharr, Weslaco, Mercedes, Harlingen, San Benito, Brownsville and South Padre Island \u2014 with local guides for buyers and sellers.',
    title: 'Explore the Rio Grande Valley',
    intro: 'McAllen isn\u2019t Edinburg isn\u2019t Weslaco. Every RGV city has its own price point, schools and pace of life \u2014 start with a neighborhood guide to find where you actually fit.',
  },
  es: {
    metaTitle: 'Bienes Ra\u00edces y Vecindarios del Valle del R\u00edo Grande | The Arper Group',
    metaDesc: 'Conoce los bienes ra\u00edces y vecindarios del Valle de Texas \u2014 McAllen, Edinburg, Mission, Pharr, Weslaco, Mercedes, Harlingen, San Benito, Brownsville y South Padre Island \u2014 con gu\u00edas locales para compradores y vendedores.',
    title: 'Conoce el Valle del R\u00edo Grande',
    intro: 'McAllen no es Edinburg, y no es Weslaco. Cada ciudad del Valle tiene su propio precio, escuelas y ritmo de vida \u2014 empieza con una gu\u00eda de zona para encontrar d\u00f3nde encajas.',
  },
};

export const about = {
  en: {
    metaTitle: 'About The Arper Group — one team, two lenses',
    metaDesc: 'A third-generation Rio Grande Valley real estate family. Mauricio brings the data, Pamela brings the potential. Less flex, more follow-through.',
    title: 'One team, two lenses.',
    intro: 'Arper is Arredondo + Perez \u2014 Mauricio and Pamela, a husband-and-wife team serving the Rio Grande Valley. He sees the data. She sees the potential. You get both.',
    storyTitle: 'Third generation, same Valley',
    story: 'Real estate runs three generations deep \u2014 from Mauricio\u2019s grandmother in Matamoros to his mother in Brownsville, and now to Mauricio and Pamela across the RGV. We built this team to make real estate feel understandable, not exclusive.',
    povTitle: 'Less flex. More follow-through.',
    pov: 'We\u2019re here to be real: grounded expertise, plain explanations, and a process that protects your ability to say no. White-glove service, rolled-up sleeves.',
    valuesTitle: 'What you can count on',
    values: [
      { h: 'Purchased, not sold', b: 'You should feel like you bought a home \u2014 not like someone sold you one.' },
      { h: 'We\u2019ll show you the work', b: 'Not \u201cwe\u2019re marketing it.\u201d Here\u2019s exactly what we did, what happened, and what changes next.' },
      { h: 'Comfortable saying no', b: 'If we think you shouldn\u2019t buy it, we\u2019ll tell you. Your goals come before our closing.' },
    ],
    peopleTitle: 'The two of us',
    people: [
      { name: 'Mauricio Arredondo', role: 'Data, marketing & investing', b: 'A product manager by background who brings market analysis and marketing systems to every listing and deal.' },
      { name: 'Pamela Perez', role: 'Property potential & design', b: 'The design eye who helps you see what a home can become \u2014 and keeps the search enjoyable.' },
    ],
  },
  es: {
    metaTitle: 'Sobre The Arper Group — un equipo, dos miradas',
    metaDesc: 'Familia de bienes raíces de tercera generación en el Valle. Mauricio aporta los datos, Pamela el potencial. Menos presumir, más cumplir.',
    title: 'Un equipo, dos miradas.',
    intro: 'Arper es Arredondo + Perez \u2014 Mauricio y Pamela, un matrimonio al servicio del Valle de Texas. Él ve los datos. Ella ve el potencial. Tú recibes ambos.',
    storyTitle: 'Tercera generación, el mismo Valle',
    story: 'Los bienes raíces vienen de tres generaciones \u2014 de la abuela de Mauricio en Matamoros, a su mamá en Brownsville, y ahora a Mauricio y Pamela en todo el Valle. Creamos este equipo para que los bienes raíces se sientan accesibles, no exclusivos.',
    povTitle: 'Menos presumir. Más cumplir.',
    pov: 'Nosotros venimos a ser reales: experiencia con los pies en la tierra, explicaciones claras, y un proceso que protege tu derecho a decir que no.',
    valuesTitle: 'Con lo que puedes contar',
    values: [
      { h: 'Comprado, no vendido', b: 'Debes sentir que compraste una casa \u2014 no que alguien te la vendió.' },
      { h: 'Te mostramos el trabajo', b: 'No \u201cya lo estamos promocionando.\u201d Esto fue exactamente lo que hicimos y lo que sigue.' },
      { h: 'Cómodos diciendo que no', b: 'Si creemos que no deberías comprarla, te lo decimos. Tus metas van antes que nuestro cierre.' },
    ],
    peopleTitle: 'Nosotros dos',
    people: [
      { name: 'Mauricio Arredondo', role: 'Datos, marketing e inversión', b: 'Product manager de formación que aporta análisis de mercado y sistemas de marketing a cada propiedad y trato.' },
      { name: 'Pamela Perez', role: 'Potencial y diseño', b: 'El ojo de diseño que te ayuda a ver en qué se puede convertir una casa \u2014 y hace la búsqueda disfrutable.' },
    ],
  },
};

export const ftb = {
  en: {
    metaTitle: 'First-time home buyers in the RGV — start with a budget, not Zillow',
    metaDesc: 'Think you can\u2019t buy yet? Before you decide, learn how down payment assistance, seller concessions and deal structure can change the picture in the Rio Grande Valley.',
    title: 'Your first step isn\u2019t Zillow. It\u2019s a budget.',
    lede: 'Buying a home is not impossible \u2014 it may be closer than you think. Before you save 40 houses, let\u2019s figure out what\u2019s actually possible for you.',
    blocks: [
      { h: 'The number keeping you from buying may not be the real number', b: 'A large down payment isn\u2019t the whole cash-to-close story. Between down payment assistance, seller concessions and how a deal is structured, there are more levers than most first-time buyers realize.' },
      { h: 'Nurses, teachers and young families: don\u2019t self-disqualify', b: 'Plenty of working households assume homeownership is only for higher earners. Don\u2019t decide you can\u2019t buy before the numbers actually say so.' },
      { h: 'You don\u2019t need to know how real estate works before calling us', b: 'Education is part of the service. You don\u2019t need a perfect plan to start the conversation \u2014 just the question you\u2019ve been putting off.' },
    ],
    faqTitle: 'First-time buyer questions',
    faqs: [
      { q: 'How much do I need for a down payment in the RGV?', a: 'It depends on the loan and the deal. Some programs allow low down payments, and down payment assistance may be available \u2014 the first step is talking with a lender to see your real options.' },
      { q: 'Do I need perfect credit to start?', a: 'No. Start the conversation early; knowing where you stand lets us build a realistic plan instead of guessing.' },
      { q: 'Should I look at homes before getting pre-approved?', a: 'Set your financial guardrails first, then shop with confidence. Browsing before knowing your buying power usually leads to disappointment.' },
    ],
    ctaTitle: 'Start with a buying plan',
    ctaBody: 'No pressure, no jargon \u2014 just a clear starting point.',
    compliance: 'We\u2019ll connect you with a lender for any financing-specific numbers. Nothing here is a promise of qualification or financing.',
  },
  es: {
    metaTitle: 'Compradores de primer hogar en el Valle — empieza con un presupuesto',
    metaDesc: '¿Crees que aún no puedes comprar? Antes de decidir, descubre cómo la ayuda para el enganche, las concesiones del vendedor y la estructura del trato pueden cambiar el panorama.',
    title: 'Tu primer paso no es Zillow. Es un presupuesto.',
    lede: 'Comprar casa no es imposible \u2014 puede estar más cerca de lo que crees. Antes de guardar 40 casas, veamos qué es realmente posible para ti.',
    blocks: [
      { h: 'El número que crees que te detiene quizá no sea el número real', b: 'Un enganche grande no es toda la historia. Entre la ayuda para el enganche, las concesiones del vendedor y cómo se estructura el trato, hay más opciones de las que la mayoría imagina.' },
      { h: 'Enfermeras, maestros y familias jóvenes: no se descalifiquen solos', b: 'Muchas familias trabajadoras creen que la casa propia es solo para quienes ganan más. No decidas que no puedes antes de ver lo que dicen los números.' },
      { h: 'No necesitas saber cómo funcionan los bienes raíces para llamarnos', b: 'Educar es parte del servicio. No necesitas un plan perfecto para empezar \u2014 solo la pregunta que has estado posponiendo.' },
    ],
    faqTitle: 'Preguntas de primer hogar',
    faqs: [
      { q: '¿Cuánto necesito para el enganche en el Valle?', a: 'Depende del préstamo y del trato. Algunos programas permiten enganches bajos y puede haber ayuda para el enganche \u2014 el primer paso es hablar con un prestamista para ver tus opciones reales.' },
      { q: '¿Necesito crédito perfecto para empezar?', a: 'No. Empieza la conversación temprano; saber dónde estás nos deja armar un plan realista en vez de adivinar.' },
      { q: '¿Debo ver casas antes de la preaprobación?', a: 'Primero define tus límites financieros y luego busca con confianza. Ver casas antes de conocer tu poder de compra suele terminar en decepción.' },
    ],
    ctaTitle: 'Empieza con un plan de compra',
    ctaBody: 'Sin presión, sin tecnicismos \u2014 solo un punto de partida claro.',
    compliance: 'Te conectamos con un prestamista para cualquier número específico de financiamiento. Nada aquí es promesa de calificación ni de financiamiento.',
  },
};

export const valuation = {
  en: {
    metaTitle: 'What\u2019s my home worth? — The Arper Group, RGV',
    metaDesc: 'Get a real read on your home\u2019s value in the Rio Grande Valley. Price from evidence, not ego.',
    title: 'What\u2019s your home worth?',
    lede: 'Price from evidence, not ego. Tell us about your home and we\u2019ll put together a grounded, market-based read \u2014 no obligation.',
    fields: { address: 'Property address', name: 'Your name', email: 'Email', phone: 'Phone (optional)', submit: 'Request my home value', sending: 'Sending\u2026' },
    success: 'Thanks \u2014 we\u2019ll be in touch soon with a market-based read on your home.',
    error: 'Something went wrong sending your request \u2014 please try again, or call/text us directly.',
    compliance: 'A home valuation is an estimate, not an appraisal or a guarantee of sale price.',
  },
  es: {
    metaTitle: '¿Cuánto vale mi casa? — The Arper Group, Valle',
    metaDesc: 'Obtén una lectura real del valor de tu casa en el Valle de Texas. Precio con evidencia, no con ego.',
    title: '¿Cuánto vale tu casa?',
    lede: 'Precio con evidencia, no con ego. Cuéntanos de tu casa y preparamos una lectura realista basada en el mercado \u2014 sin compromiso.',
    fields: { address: 'Dirección de la propiedad', name: 'Tu nombre', email: 'Correo', phone: 'Teléfono (opcional)', submit: 'Quiero el valor de mi casa', sending: 'Enviando\u2026' },
    success: 'Gracias \u2014 pronto te contactamos con una lectura de tu casa basada en el mercado.',
    error: 'Algo salió mal al enviar tu solicitud \u2014 intenta de nuevo, o mejor márcanos o escríbenos directo.',
    compliance: 'Una valuación es una estimación, no un avalúo ni una garantía de precio de venta.',
  },
};

export const resources = {
  en: {
    metaTitle: 'Free real estate calculators & resources — RGV | The Arper Group',
    metaDesc: 'Free tools for buying, selling and investing in the Rio Grande Valley — starting with our mortgage calculator, with more calculators on the way.',
    title: 'Resources',
    lede: 'Free tools to help you plan your next move in the Rio Grande Valley — starting with the numbers.',
    liveLabel: 'Available now',
    soonLabel: 'Coming soon',
    cards: [
      { title: 'Mortgage Calculator', body: 'Estimate your monthly payment with today’s rates, RGV property taxes, and PMI.', href: '/en/resources/mortgage-calculator', cta: 'Calculate your payment', live: true },
      { title: 'Seller Net Proceeds', body: 'See what you could walk away with after paying off your loan, agent fees and closing costs.', href: '/en/resources/seller-net-proceeds', cta: 'Estimate your proceeds', live: true },
      { title: 'Closing Cost Estimator', body: 'A clearer picture of what you’ll pay — or receive — at the closing table.', href: '/en/resources/closing-cost-estimator', cta: 'Estimate your cash to close', live: true },
      { title: 'Title Policy Calculator', body: 'Estimate Texas title insurance premiums for your purchase price.', live: false },
      { title: 'Investment Property Calculator', body: 'Run the numbers on cash flow, cap rate and return before you make an offer.', live: false },
      { title: 'Flip Calculator', body: 'Budget your purchase, rehab and holding costs against your resale target.', live: false },
    ],
  },
  es: {
    metaTitle: 'Calculadoras y recursos gratis de bienes raíces — Valle | The Arper Group',
    metaDesc: 'Herramientas gratis para comprar, vender e invertir en el Valle de Texas — empezando con nuestra calculadora de hipoteca, con más en camino.',
    title: 'Recursos',
    lede: 'Herramientas gratis para planear tu siguiente paso en el Valle — empezando por los números.',
    liveLabel: 'Disponible ahora',
    soonLabel: 'Muy pronto',
    cards: [
      { title: 'Calculadora de Hipoteca', body: 'Calcula tu pago mensual con las tasas de hoy, los impuestos prediales del Valle, y el PMI.', href: '/es/resources/mortgage-calculator', cta: 'Calcula tu pago', live: true },
      { title: 'Ganancia Neta del Vendedor', body: 'Mira con cuánto te podrías quedar después de liquidar tu préstamo, las comisiones y los costos de cierre.', href: '/es/resources/seller-net-proceeds', cta: 'Calcula tu ganancia', live: true },
      { title: 'Estimador de Costos de Cierre', body: 'Una idea más clara de lo que pagarás — o recibirás — en la mesa de cierre.', href: '/es/resources/closing-cost-estimator', cta: 'Calcula tu efectivo al cierre', live: true },
      { title: 'Calculadora de Póliza de Título', body: 'Estima la prima del seguro de título en Texas para tu precio de compra.', live: false },
      { title: 'Calculadora de Propiedad de Inversión', body: 'Calcula el flujo de efectivo, el cap rate y el retorno antes de hacer una oferta.', live: false },
      { title: 'Calculadora de Flip', body: 'Presupuesta tu compra, remodelación y costos de espera contra tu meta de reventa.', live: false },
    ],
  },
};

export const mortgageCalc = {
  en: {
    metaTitle: 'Mortgage Calculator — RGV & McAllen Home Loan Payments | The Arper Group',
    metaDesc: 'Estimate your monthly mortgage payment for a home in McAllen or the Rio Grande Valley, with today’s rates, local property taxes, and PMI — free, no signup required.',
    kicker: 'Free tool · no signup',
    title: 'Mortgage calculator',
    lede: 'See what a home in the Rio Grande Valley could cost you each month — today’s rates, local property taxes, and PMI, all in one place.',
    labels: {
      homePrice: 'Home price',
      downPayment: 'Down payment',
      interestRate: 'Interest rate',
      loanTerm: 'Loan term',
      yr: 'yr',
      city: 'City / area',
      otherCity: 'Other RGV',
      advancedShow: 'Advanced options',
      advancedHide: 'Hide advanced options',
      propertyTax: 'Property tax (annual)',
      homeInsurance: 'Home insurance (annual)',
      hoa: 'HOA (monthly)',
      pmi: 'PMI (annual)',
      pmiHint: 'Applied automatically when your down payment is under 20% — you can edit it.',
    },
    rateNote: 'Today’s national average (Freddie Mac), as of {date} — your rate will vary and is editable.',
    taxNote: 'Estimated from the typical combined rate for {city} — a homestead exemption and your appraised value will change this; confirm with the county appraisal district.',
    results: {
      title: 'Your estimated payment',
      monthlyPayment: 'Estimated monthly payment',
      principalInterest: 'Principal & interest',
      taxes: 'Property taxes',
      insurance: 'Home insurance',
      pmi: 'PMI',
      hoa: 'HOA',
      totalInterest: 'Total interest over the loan',
      loanAmount: 'Loan amount',
      perMonth: '/mo',
    },
    disclaimer: 'This is an estimate, not a loan quote or a commitment to lend. Property taxes are estimated and vary by exemptions and appraised value. Connect with a lender for exact figures.',
    lead: {
      cta: 'Text me these numbers & today’s rate options',
      name: 'Name',
      phone: 'Phone',
      submit: 'Send me my numbers',
      sending: 'Sending…',
      consent: 'By submitting, you agree to be contacted by call or text about your inquiry. Msg/data rates may apply.',
      success: 'Thanks — we’ll text or call you shortly with these numbers and today’s rate options.',
      error: 'Something went wrong sending your request — please try again, or call/text us directly.',
    },
    faqTitle: 'Mortgage calculator questions',
    faqs: [
      { q: 'How much is a monthly mortgage payment in the RGV?', a: 'It depends on the price, your down payment, your rate, and local property taxes — which vary by city. Use the calculator above with your numbers, or a nearby city, to get a real estimate in seconds.' },
      { q: 'Why are Rio Grande Valley property taxes higher?', a: 'Texas has no state income tax, so property taxes carry more of the load for schools, cities and counties. Combined rates across the RGV typically run around 2%–2.3% of appraised value, though a homestead exemption can lower what you actually owe.' },
      { q: 'How much down payment do I need?', a: 'Putting down 20% avoids private mortgage insurance (PMI), but plenty of buyers put down far less through conventional, FHA or VA financing. We’ll connect you with a lender to see what you actually qualify for.' },
    ],
  },
  es: {
    metaTitle: 'Calculadora de Hipoteca — Pagos de Casa en el Valle y McAllen | The Arper Group',
    metaDesc: 'Calcula el pago mensual estimado de tu hipoteca en McAllen o el Valle de Texas, con las tasas de hoy, impuestos prediales locales y PMI — gratis, sin registro.',
    kicker: 'Herramienta gratis · sin registro',
    title: 'Calculadora de hipoteca',
    lede: 'Descubre cuánto podría costarte una casa en el Valle cada mes — las tasas de hoy, los impuestos prediales locales y el PMI, todo en un solo lugar.',
    labels: {
      homePrice: 'Precio de la casa',
      downPayment: 'Enganche',
      interestRate: 'Tasa de interés',
      loanTerm: 'Plazo del préstamo',
      yr: 'años',
      city: 'Ciudad / zona',
      otherCity: 'Otro RGV',
      advancedShow: 'Opciones avanzadas',
      advancedHide: 'Ocultar opciones avanzadas',
      propertyTax: 'Impuesto predial (anual)',
      homeInsurance: 'Seguro de la casa (anual)',
      hoa: 'Cuota HOA (mensual)',
      pmi: 'PMI (anual)',
      pmiHint: 'Se aplica automáticamente cuando el enganche es menor al 20% — puedes editarlo.',
    },
    rateNote: 'Promedio nacional de hoy (Freddie Mac), al {date} — tu tasa puede variar y es editable.',
    taxNote: 'Estimado con la tasa combinada típica de {city} — una exención de homestead y tu valor catastral cambian esto; confírmalo con el distrito de valuación del condado.',
    results: {
      title: 'Tu pago estimado',
      monthlyPayment: 'Pago mensual estimado',
      principalInterest: 'Capital e interés',
      taxes: 'Impuesto predial',
      insurance: 'Seguro de la casa',
      pmi: 'PMI',
      hoa: 'HOA',
      totalInterest: 'Interés total del préstamo',
      loanAmount: 'Monto del préstamo',
      perMonth: '/mes',
    },
    disclaimer: 'Esto es una estimación, no una cotización de préstamo ni un compromiso de financiamiento. Los impuestos prediales son estimados y varían según exenciones y el valor catastral. Conéctate con un prestamista para cifras exactas.',
    lead: {
      cta: 'Envíame estos números y las tasas de hoy',
      name: 'Nombre',
      phone: 'Teléfono',
      submit: 'Envíame mis números',
      sending: 'Enviando…',
      consent: 'Al enviar, aceptas que te contactemos por llamada o mensaje de texto sobre tu consulta. Pueden aplicar tarifas de mensajes/datos.',
      success: 'Gracias — te llamamos o mandamos mensaje pronto con estos números y las tasas de hoy.',
      error: 'Algo salió mal al enviar tu solicitud — intenta de nuevo, o mejor márcanos o escríbenos directo.',
    },
    faqTitle: 'Preguntas sobre la calculadora de hipoteca',
    faqs: [
      { q: '¿Cuánto es el pago mensual de una hipoteca en el Valle?', a: 'Depende del precio, tu enganche, tu tasa y los impuestos prediales locales — que varían según la ciudad. Usa la calculadora de arriba con tus números, o los de una ciudad cercana, para una estimación real en segundos.' },
      { q: '¿Por qué son más altos los impuestos prediales en el Valle?', a: 'Texas no tiene impuesto estatal sobre la renta, así que el impuesto predial carga más del peso para escuelas, ciudades y condados. Las tasas combinadas en el Valle suelen rondar entre 2% y 2.3% del valor catastral, aunque una exención de homestead puede bajar lo que realmente debes.' },
      { q: '¿Cuánto enganche necesito?', a: 'Dar el 20% evita el seguro hipotecario privado (PMI), pero muchos compradores dan mucho menos con financiamiento convencional, FHA o VA. Te conectamos con un prestamista para ver para qué calificas realmente.' },
    ],
  },
};

export const sellerNetProceeds = {
  en: {
    metaTitle: "Seller Net Proceeds Calculator — What You'll Walk Away With | The Arper Group",
    metaDesc: 'Estimate your net proceeds from selling a home in the Rio Grande Valley — loan payoff, commission, Texas title insurance and closing costs, all in one place.',
    kicker: 'Free tool · no signup',
    title: 'Seller net proceeds calculator',
    lede: "See roughly what you'd walk away with after your loan payoff, commission, title insurance and closing costs — before you decide to list.",
    labels: {
      salePrice: 'Estimated sale price',
      loanPayoff: 'Mortgage payoff (all loans)',
      commission: 'Total commission',
      city: 'City / area',
      otherCity: 'Other RGV',
      closingDate: 'Estimated closing date',
      titleInsurance: "Owner's title policy",
      buyerPaysTitle: "Buyer is paying for the owner's policy instead",
      advancedShow: 'Advanced options',
      advancedHide: 'Hide advanced options',
      annualTax: 'Annual property tax',
      hoaFee: 'HOA transfer / resale certificate fee',
      homeWarranty: 'Home warranty (optional)',
      closingFees: 'Closing, escrow & recording fees',
      sellerConcessions: "Seller concessions (buyer's closing costs)",
    },
    titleNote: "Based on the sale price — Texas' promulgated rate for a {price} owner's policy, set by the Texas Department of Insurance (effective March 1, 2026). The buyer's separate loan policy is based on their loan amount and is customarily paid by the buyer, not the seller.",
    taxNote: 'Estimated from the typical combined rate for {city} — confirm with the county appraisal district.',
    commissionNote: "Not set by law and fully negotiable with your agent — brokerages are required to disclose this under the 2024 NAR settlement. Texas commissions averaged about 5.9% combined in 2026; 6% is a common starting point.",
    closingFeesNote: 'Typical range $200–$600 — your title company will confirm the exact amount.',
    warrantyNote: 'Typically $450–$600 if you choose to offer one.',
    concessionsNote: "A credit toward the buyer's closing costs or rate buy-down — a common negotiating tool, especially in a buyer's market.",
    results: {
      title: 'Your estimated net proceeds',
      salePrice: 'Sale price',
      loanPayoff: 'Mortgage payoff',
      commission: 'Commission',
      titleInsurance: "Owner's title policy",
      taxCredit: 'Property tax credit to buyer',
      hoaFee: 'HOA transfer fee',
      homeWarranty: 'Home warranty',
      closingFees: 'Closing & recording fees',
      sellerConcessions: 'Seller concessions',
      net: 'Estimated net proceeds',
    },
    disclaimer: 'This is an estimate, not a net sheet or a commitment to sell. Your actual loan payoff, commission and closing costs will be confirmed by your lender and title company. Not tax or legal advice.',
    lead: {
      cta: 'Text me these numbers & a real net sheet',
      name: 'Name',
      phone: 'Phone',
      submit: 'Send me my numbers',
      sending: 'Sending…',
      consent: 'By submitting, you agree to be contacted by call or text about your inquiry. Msg/data rates may apply.',
      success: "Thanks — we'll text or call you shortly with a real net sheet for your home.",
      error: 'Something went wrong sending your request — please try again, or call/text us directly.',
    },
    faqTitle: 'Seller net proceeds questions',
    faqs: [
      { q: 'How much does it cost to sell a house in the RGV?', a: "Between commission, title insurance and closing costs, most RGV sellers net somewhere around 6%–9% below their sale price — though it varies with your loan payoff, price, and what you negotiate. Use the calculator above with your numbers for a real estimate." },
      { q: 'Who pays for title insurance in Texas?', a: "By statewide custom, the seller pays for the buyer's owner's title policy — though like most closing costs, it's negotiable. Texas title insurance premiums are set by the state (promulgated rates), so the price is the same no matter which title company you use." },
      { q: "What's the difference between my loan balance and my payoff?", a: "Your payoff is higher than your current balance — it includes interest that accrues up to your closing date, plus any fees. Your lender can give you a payoff quote good through a specific date once you're under contract." },
    ],
  },
  es: {
    metaTitle: 'Calculadora de Ganancia Neta del Vendedor — Cuánto Te Quedas | The Arper Group',
    metaDesc: 'Calcula tu ganancia neta al vender tu casa en el Valle de Texas — liquidación de tu préstamo, comisión, seguro de título y costos de cierre, todo en un solo lugar.',
    kicker: 'Herramienta gratis · sin registro',
    title: 'Calculadora de ganancia neta del vendedor',
    lede: 'Mira aproximadamente con cuánto te quedarías después de liquidar tu préstamo, la comisión, el seguro de título y los costos de cierre — antes de decidir poner tu casa en venta.',
    labels: {
      salePrice: 'Precio de venta estimado',
      loanPayoff: 'Liquidación de préstamo(s)',
      commission: 'Comisión total',
      city: 'Ciudad / zona',
      otherCity: 'Otro RGV',
      closingDate: 'Fecha de cierre estimada',
      titleInsurance: 'Póliza de título del propietario',
      buyerPaysTitle: 'El comprador paga la póliza en lugar del vendedor',
      advancedShow: 'Opciones avanzadas',
      advancedHide: 'Ocultar opciones avanzadas',
      annualTax: 'Impuesto predial anual',
      hoaFee: 'Cuota de transferencia HOA / certificado de reventa',
      homeWarranty: 'Garantía de la casa (opcional)',
      closingFees: 'Cierre, escrow y gastos de registro',
      sellerConcessions: 'Concesiones del vendedor (costos de cierre del comprador)',
    },
    titleNote: 'Basada en el precio de venta — tarifa promulgada de Texas para una póliza de {price}, fijada por el Departamento de Seguros de Texas (vigente desde el 1 de marzo de 2026). La póliza de préstamo del comprador es aparte, se basa en el monto de su préstamo y normalmente la paga el comprador.',
    taxNote: 'Estimado con la tasa combinada típica de {city} — confírmalo con el distrito de valuación del condado.',
    commissionNote: 'No la fija la ley y es totalmente negociable con tu agente — desde el acuerdo NAR de 2024, las inmobiliarias deben aclarar que la comisión se negocia. Las comisiones en Texas promediaron cerca de 5.9% combinado en 2026; el 6% sigue siendo un punto de partida común.',
    closingFeesNote: 'Rango típico $200–$600 — tu compañía de título te confirma el monto exacto.',
    warrantyNote: 'Normalmente $450–$600 si decides ofrecer una.',
    concessionsNote: 'Un crédito hacia los costos de cierre del comprador o para bajar su tasa — una herramienta común de negociación, sobre todo en un mercado de compradores.',
    results: {
      title: 'Tu ganancia neta estimada',
      salePrice: 'Precio de venta',
      loanPayoff: 'Liquidación del préstamo',
      commission: 'Comisión',
      titleInsurance: 'Póliza de título del propietario',
      taxCredit: 'Crédito de impuesto predial al comprador',
      hoaFee: 'Cuota de transferencia HOA',
      homeWarranty: 'Garantía de la casa',
      closingFees: 'Cierre y registro',
      sellerConcessions: 'Concesiones del vendedor',
      net: 'Ganancia neta estimada',
    },
    disclaimer: 'Esto es una estimación, no una hoja neta ni un compromiso de vender. Tu liquidación real, comisión y costos de cierre serán confirmados por tu prestamista y tu compañía de título. No es asesoría fiscal ni legal.',
    lead: {
      cta: 'Envíame estos números y una hoja neta real',
      name: 'Nombre',
      phone: 'Teléfono',
      submit: 'Envíame mis números',
      sending: 'Enviando…',
      consent: 'Al enviar, aceptas que te contactemos por llamada o mensaje de texto sobre tu consulta. Pueden aplicar tarifas de mensajes/datos.',
      success: 'Gracias — te llamamos o mandamos mensaje pronto con una hoja neta real para tu casa.',
      error: 'Algo salió mal al enviar tu solicitud — intenta de nuevo, o mejor márcanos o escríbenos directo.',
    },
    faqTitle: 'Preguntas sobre ganancia neta del vendedor',
    faqs: [
      { q: '¿Cuánto cuesta vender una casa en el Valle?', a: 'Entre comisión, seguro de título y costos de cierre, la mayoría de los vendedores del Valle terminan quedándose con un 6%–9% menos del precio de venta — aunque varía según tu liquidación, el precio y lo que negocies. Usa la calculadora de arriba con tus números para una estimación real.' },
      { q: '¿Quién paga el seguro de título en Texas?', a: 'Por costumbre en todo el estado, el vendedor paga la póliza de título del propietario para el comprador — aunque, como la mayoría de los costos de cierre, es negociable. Las primas de seguro de título en Texas las fija el estado (tarifa promulgada), así que el precio es el mismo sin importar qué compañía de título uses.' },
      { q: '¿Cuál es la diferencia entre el saldo de mi préstamo y mi liquidación?', a: 'Tu liquidación es más alta que tu saldo actual — incluye el interés que se acumula hasta tu fecha de cierre, más cualquier cargo. Tu prestamista te puede dar una cotización de liquidación válida hasta una fecha específica una vez que estés bajo contrato.' },
    ],
  },
};

export const closingCost = {
  en: {
    metaTitle: 'Buyer Closing Cost Estimator — Cash to Close in the RGV | The Arper Group',
    metaDesc: "Estimate what you'll need at closing for a home in the Rio Grande Valley — down payment, lender fees, title insurance, prepaids and escrow reserves, all in one place.",
    kicker: 'Free tool · no signup',
    title: 'Buyer closing cost estimator',
    lede: "See roughly what you'd need at the closing table — down payment plus lender fees, title insurance, prepaid items and escrow reserves.",
    labels: {
      salePrice: 'Purchase price',
      downPayment: 'Down payment',
      interestRate: 'Interest rate',
      city: 'City / area',
      otherCity: 'Other RGV',
      closingDate: 'Estimated closing date',
      advancedShow: 'Advanced options',
      advancedHide: 'Hide advanced options',
      originationPercent: 'Loan origination fee',
      appraisalFee: 'Appraisal fee',
      lenderFees: 'Other lender fees (credit report, underwriting)',
      titlePolicy: "Buyer's loan title policy",
      recordingFees: 'Recording fees',
      homeInsurance: 'Homeowners insurance (first year)',
      escrowMonths: 'Tax & insurance escrow reserve (months)',
      hoaFee: "HOA transfer fee (if you're covering it)",
      surveyFee: 'Survey (optional)',
    },
    originationNote: "Typically 0%–1% of your loan amount — your lender's Loan Estimate will have the exact figure.",
    titlePolicyNote: "Texas' simultaneous-issue rate (Rate Rule R-5) for a buyer's loan policy issued alongside a seller-paid owner's policy — a flat rate set by the state, per the Texas Department of Insurance.",
    interestNote: 'Per-diem interest from your closing date through the end of that month, at your rate above.',
    escrowNote: 'Lenders typically collect a few months of taxes and insurance upfront as a cushion — this varies by lender and closing timing.',
    taxNote: 'Estimated from the typical combined rate for {city} — confirm with the county appraisal district.',
    rateNote: 'Today’s national average (Freddie Mac), as of {date} — your rate will vary and is editable.',
    surveyNote: 'Typically $400–$700 if you order a new one; sometimes the seller’s existing survey can be used instead.',
    results: {
      title: 'Your estimated cash to close',
      downPayment: 'Down payment',
      origination: 'Loan origination',
      appraisal: 'Appraisal fee',
      lenderFees: 'Other lender fees',
      titlePolicy: 'Loan title policy',
      recordingFees: 'Recording fees',
      homeInsurance: 'Homeowners insurance',
      prepaidInterest: 'Prepaid interest',
      escrowReserve: 'Tax & insurance escrow reserve',
      hoaFee: 'HOA transfer fee',
      surveyFee: 'Survey',
      closingCostsSubtotal: 'Closing costs subtotal',
      total: 'Estimated cash to close',
    },
    disclaimer: "This is an estimate, not a Loan Estimate or Closing Disclosure. Your lender and title company will confirm exact figures once you're under contract. Not tax or legal advice.",
    lead: {
      cta: 'Text me these numbers & help finding a lender',
      name: 'Name',
      phone: 'Phone',
      submit: 'Send me my numbers',
      sending: 'Sending…',
      consent: 'By submitting, you agree to be contacted by call or text about your inquiry. Msg/data rates may apply.',
      success: "Thanks — we'll text or call you shortly with these numbers and a lender referral.",
      error: 'Something went wrong sending your request — please try again, or call/text us directly.',
    },
    faqTitle: 'Closing cost questions',
    faqs: [
      { q: 'How much are closing costs for buyers in Texas?', a: "Most Texas buyers pay somewhere between 2% and 4% of the loan amount in closing costs, on top of the down payment — though it varies with your lender, loan type and the home's price. Use the calculator above with your numbers for a real estimate." },
      { q: 'When do I get exact numbers instead of an estimate?', a: "Once you're under contract, your lender is required to send a Loan Estimate within three business days, and a final Closing Disclosure at least three days before closing — those will have your exact figures." },
      { q: "Why do I need an escrow reserve if I'm already paying my taxes and insurance?", a: "Your lender collects a cushion of a few months' worth upfront so your escrow account never runs short before your first regular payments catch up — it's part of your loan, not an extra cost that disappears." },
    ],
  },
  es: {
    metaTitle: 'Estimador de Costos de Cierre para Compradores — Efectivo al Cierre en el Valle | The Arper Group',
    metaDesc: 'Calcula lo que necesitarás al cierre para una casa en el Valle de Texas — enganche, cargos del prestamista, seguro de título, prepagos y reservas de escrow, todo en un solo lugar.',
    kicker: 'Herramienta gratis · sin registro',
    title: 'Estimador de costos de cierre para compradores',
    lede: 'Mira aproximadamente lo que necesitarías en la mesa de cierre — el enganche más los cargos del prestamista, el seguro de título, los prepagos y las reservas de escrow.',
    labels: {
      salePrice: 'Precio de compra',
      downPayment: 'Enganche',
      interestRate: 'Tasa de interés',
      city: 'Ciudad / zona',
      otherCity: 'Otro RGV',
      closingDate: 'Fecha de cierre estimada',
      advancedShow: 'Opciones avanzadas',
      advancedHide: 'Ocultar opciones avanzadas',
      originationPercent: 'Cargo de originación del préstamo',
      appraisalFee: 'Costo del avalúo',
      lenderFees: 'Otros cargos del prestamista (reporte de crédito, suscripción)',
      titlePolicy: 'Póliza de título del préstamo (comprador)',
      recordingFees: 'Cargos de registro',
      homeInsurance: 'Seguro de la casa (primer año)',
      escrowMonths: 'Reserva de escrow de impuestos y seguro (meses)',
      hoaFee: 'Cuota de transferencia HOA (si tú la cubres)',
      surveyFee: 'Levantamiento topográfico (opcional)',
    },
    originationNote: 'Normalmente 0%–1% de tu préstamo — el Loan Estimate de tu prestamista tendrá la cifra exacta.',
    titlePolicyNote: 'Tarifa de emisión simultánea de Texas (Regla de Tarifa R-5) para la póliza de préstamo del comprador emitida junto con una póliza del propietario pagada por el vendedor — una tarifa fija que fija el estado, según el Departamento de Seguros de Texas.',
    interestNote: 'Interés diario desde tu fecha de cierre hasta el fin de ese mes, con la tasa de arriba.',
    escrowNote: 'Los prestamistas normalmente juntan varios meses de impuestos y seguro por adelantado como colchón — esto varía según el prestamista y la fecha de cierre.',
    taxNote: 'Estimado con la tasa combinada típica de {city} — confírmalo con el distrito de valuación del condado.',
    rateNote: 'Promedio nacional de hoy (Freddie Mac), al {date} — tu tasa puede variar y es editable.',
    surveyNote: 'Normalmente $400–$700 si pides uno nuevo; a veces se puede usar el levantamiento existente del vendedor.',
    results: {
      title: 'Tu efectivo estimado para el cierre',
      downPayment: 'Enganche',
      origination: 'Originación del préstamo',
      appraisal: 'Costo del avalúo',
      lenderFees: 'Otros cargos del prestamista',
      titlePolicy: 'Póliza de título del préstamo',
      recordingFees: 'Cargos de registro',
      homeInsurance: 'Seguro de la casa',
      prepaidInterest: 'Interés prepagado',
      escrowReserve: 'Reserva de escrow de impuestos y seguro',
      hoaFee: 'Cuota de transferencia HOA',
      surveyFee: 'Levantamiento topográfico',
      closingCostsSubtotal: 'Subtotal de costos de cierre',
      total: 'Efectivo estimado para el cierre',
    },
    disclaimer: 'Esto es una estimación, no un Loan Estimate ni un Closing Disclosure. Tu prestamista y tu compañía de título confirmarán las cifras exactas una vez que estés bajo contrato. No es asesoría fiscal ni legal.',
    lead: {
      cta: 'Envíame estos números y ayuda para encontrar un prestamista',
      name: 'Nombre',
      phone: 'Teléfono',
      submit: 'Envíame mis números',
      sending: 'Enviando…',
      consent: 'Al enviar, aceptas que te contactemos por llamada o mensaje de texto sobre tu consulta. Pueden aplicar tarifas de mensajes/datos.',
      success: 'Gracias — te llamamos o mandamos mensaje pronto con estos números y una recomendación de prestamista.',
      error: 'Algo salió mal al enviar tu solicitud — intenta de nuevo, o mejor márcanos o escríbenos directo.',
    },
    faqTitle: 'Preguntas sobre costos de cierre',
    faqs: [
      { q: '¿Cuánto son los costos de cierre para compradores en Texas?', a: 'La mayoría de los compradores en Texas pagan entre 2% y 4% del monto del préstamo en costos de cierre, además del enganche — aunque varía según tu prestamista, el tipo de préstamo y el precio de la casa. Usa la calculadora de arriba con tus números para una estimación real.' },
      { q: '¿Cuándo recibo números exactos en lugar de una estimación?', a: 'Una vez que estés bajo contrato, tu prestamista debe enviarte un Loan Estimate dentro de tres días hábiles, y un Closing Disclosure final al menos tres días antes del cierre — esos tendrán tus cifras exactas.' },
      { q: '¿Por qué necesito una reserva de escrow si ya pago mis impuestos y seguro?', a: 'Tu prestamista junta un colchón de varios meses por adelantado para que tu cuenta de escrow nunca se quede corta antes de que tus pagos regulares se pongan al día — es parte de tu préstamo, no un costo extra que desaparece.' },
    ],
  },
};

export const cities = {
  mcallen: {
    en: {
      name: 'McAllen', metaTitle: 'Living in McAllen, TX — a local real estate guide',
      metaDesc: 'What it\u2019s like to live in McAllen, Texas: neighborhoods, cost of living, schools, property taxes and lifestyle, from a local RGV real estate team.',
      intro: 'McAllen is the commercial heart of the Rio Grande Valley \u2014 a bilingual, cross-border city known for retail, healthcare and a cost of living that still surprises people moving in from bigger metros.',
      sections: [
        { h: 'Cost of living', b: 'Housing generally runs well below Texas\u2019s big metros, though prices vary block to block. What your budget buys in McAllen looks different than in Edinburg or Weslaco \u2014 worth comparing before you commit.' },
        { h: 'Schools', b: 'McAllen ISD anchors the city, with several other districts nearby. Families weigh school boundaries alongside commute and neighborhood \u2014 tell us what needs to be close and we\u2019ll help you compare.' },
        { h: 'Property taxes', b: 'Texas has no state income tax, so property taxes carry more of the load. Rates vary by district and exemptions matter \u2014 we\u2019ll walk you through what to expect for a given home.' },
        { h: 'Lifestyle', b: 'Expect warm winters, strong food and shopping, quick access to South Padre, and an easy cross-border rhythm. Ten miles in the RGV can change the whole fit.' },
      ],
      picks: [
        { category: 'Eat-casual', place: 'Piquin', where: 'North 10th St', why: 'Tacos al pastor — it\'s a real trompo! Couldn\'t get more authentic.', pickedBy: 'Mau' },
        { category: 'Upscale bar', place: 'Toloa Rooftop', where: 'North 10th St', why: 'Their new Black Buffalo Chicken is ridiculously good!', pickedBy: 'Pam' },
        { category: 'Eat-upscale', place: 'Salt - New American Table', why: 'I used to work there as a hostess — awesome date night spot', pickedBy: 'Pam' },
        { category: 'Coffee & sweets', place: 'Human Bean Coffee', pickedBy: 'Pam' },
        { category: 'Museum', place: 'IMAS', pickedBy: 'Pam' },
        { category: 'Park / outdoors', place: 'Santa Ana Wildlife Refuge', pickedBy: 'Pam' },
        { category: 'Park / outdoors', place: 'Quinta Mazatlan', pickedBy: 'Pam' },
        { category: 'Playhouse / family', place: 'We Rock the Spectrum', pickedBy: 'Pam' },
        { category: 'Playhouse / family', place: 'Teddy\'s Playhouse', pickedBy: 'Pam' },
        { category: 'Eat-upscale', place: 'Mujinzo', pickedBy: 'Pam' },
        { category: 'Eat-casual', place: 'Greens and Lemons', pickedBy: 'Mau & Pam' },
        { category: 'Fitness', place: 'ARRI Fitness', pickedBy: 'Mau & Pam' },
        { category: 'Eat-casual', place: 'Golden Ice Cream', why: 'Our favorite ice cream in town — the no-sugar-added vanilla option is great for the little ones.', pickedBy: 'Mau & Pam' },
        { category: 'Shopping', place: 'La Plaza Mall', pickedBy: 'Pam' },
        { category: 'Shopping', place: 'Sylvia\'s', pickedBy: 'Pam' },
        { category: 'Shopping', place: 'OH Kay\'s', pickedBy: 'Pam' },
        { category: 'Shopping', place: 'Orange Turtle', pickedBy: 'Pam' },
        { category: 'Eat-casual', place: 'Fares', pickedBy: 'Pam' },
        { category: 'Pool service', place: 'Jeremy Hiller Pools', why: 'Hands down, best pool service we\'ve worked with!', pickedBy: 'Mau & Pam' },
        { category: 'Health', place: 'Integrative Rheumatology of STX', pickedBy: 'Pam' },
        { category: 'Hobbies', place: 'Sew Fun with Mrs. Morrow', pickedBy: 'Pam' },
        { category: 'Hobbies', place: 'Music Fun with Mr. Morrow', pickedBy: 'Pam' },
      ],
    },
    es: {
      name: 'McAllen', metaTitle: 'Vivir en McAllen, TX — guía local de bienes raíces',
      metaDesc: 'Cómo es vivir en McAllen, Texas: zonas, costo de vida, escuelas, impuestos prediales y estilo de vida, de un equipo local del Valle.',
      intro: 'McAllen es el corazón comercial del Valle \u2014 una ciudad bilingüe y fronteriza conocida por su comercio, su sector salud y un costo de vida que todavía sorprende a quienes llegan de ciudades más grandes.',
      sections: [
        { h: 'Costo de vida', b: 'La vivienda suele estar muy por debajo de las grandes ciudades de Texas, aunque el precio cambia de cuadra en cuadra. Lo que tu presupuesto compra en McAllen no es lo mismo que en Edinburg o Weslaco \u2014 conviene comparar.' },
        { h: 'Escuelas', b: 'McAllen ISD ancla la ciudad, con varios distritos cerca. Las familias pesan los límites escolares junto con el traslado y la zona \u2014 dinos qué necesita quedar cerca y te ayudamos a comparar.' },
        { h: 'Impuestos prediales', b: 'Texas no tiene impuesto estatal sobre la renta, así que el predial pesa más. Las tasas cambian por distrito y las exenciones importan \u2014 te explicamos qué esperar para cada casa.' },
        { h: 'Estilo de vida', b: 'Inviernos cálidos, buena comida y comercio, South Padre a la vuelta, y un ritmo fronterizo natural. Diez millas en el Valle cambian todo.' },
      ],
    },
  },
  edinburg: {
    en: {
      name: 'Edinburg', metaTitle: 'Living in Edinburg, TX — a local real estate guide',
      metaDesc: 'What it\u2019s like to live in Edinburg, Texas: neighborhoods, cost of living, schools, property taxes and lifestyle, from a local RGV real estate team.',
      intro: 'Edinburg is the county seat and one of the Valley\u2019s fastest-growing cities \u2014 home to UTRGV, newer master-planned neighborhoods, and a steady stream of families moving north from McAllen for space.',
      sections: [
        { h: 'Cost of living', b: 'Newer construction and more land often mean you get more square footage for the money than in central McAllen \u2014 with trade-offs in commute and established amenities. We\u2019ll compare real options side by side.' },
        { h: 'Schools', b: 'Edinburg CISD and the presence of UTRGV shape the city. Growth corridors mean new schools and shifting boundaries \u2014 something to check for any specific address.' },
        { h: 'Property taxes', b: 'As with the rest of Texas, no state income tax pushes more onto property taxes; newer developments can carry additional district assessments worth understanding before you buy.' },
        { h: 'Lifestyle', b: 'A university-town energy, newer parks and retail, and quick access to the rest of the Valley. What sells in McAllen isn\u2019t automatically what sells in Edinburg \u2014 local nuance matters.' },
      ],
      picks: [
        { category: 'Sports bar', place: 'Skybar Sports Lounge', pickedBy: 'Mau' },
        { category: 'Eat-casual', place: 'University Drafthouse', pickedBy: 'Mau' },
        { category: 'Park / outdoors', place: 'Edinburg Municipal Park', pickedBy: 'Mau & Pam' },
        { category: 'Pool service', place: 'Jeremy Hiller Pools', why: 'Hands down, best pool service we\'ve worked with!', pickedBy: 'Mau & Pam' },
        { category: 'Health', place: 'Premier Valley Health', pickedBy: 'Mau' },
      ],
    },
    es: {
      name: 'Edinburg', metaTitle: 'Vivir en Edinburg, TX — guía local de bienes raíces',
      metaDesc: 'Cómo es vivir en Edinburg, Texas: zonas, costo de vida, escuelas, impuestos prediales y estilo de vida, de un equipo local del Valle.',
      intro: 'Edinburg es la cabecera del condado y una de las ciudades que más crece en el Valle \u2014 hogar de UTRGV, fraccionamientos nuevos, y familias que suben desde McAllen buscando espacio.',
      sections: [
        { h: 'Costo de vida', b: 'La construcción nueva y más terreno suelen darte más metros por tu dinero que el centro de McAllen \u2014 con sus concesiones en traslado y servicios establecidos. Comparamos opciones reales lado a lado.' },
        { h: 'Escuelas', b: 'Edinburg CISD y la presencia de UTRGV marcan la ciudad. Los corredores de crecimiento traen escuelas nuevas y límites que cambian \u2014 conviene revisarlo para cada dirección.' },
        { h: 'Impuestos prediales', b: 'Como en el resto de Texas, sin impuesto estatal el predial pesa más; los desarrollos nuevos pueden traer cuotas de distrito adicionales que vale la pena entender antes de comprar.' },
        { h: 'Estilo de vida', b: 'Energía de ciudad universitaria, parques y comercio nuevos, y acceso rápido al resto del Valle. Lo que se vende en McAllen no es automáticamente lo que se vende en Edinburg \u2014 el matiz local importa.' },
      ],
    },
  },

  mission: {
    en: {
      name: 'Mission', metaTitle: 'Living in Mission, TX — a local real estate guide',
      metaDesc: 'What it\u2019s like to live in Mission, Texas: neighborhoods, cost of living, schools, property taxes and lifestyle, from a local RGV real estate team.',
      intro: 'Just west of McAllen, Mission blends established neighborhoods with newer growth and a strong citrus heritage \u2014 it\u2019s long been known as the Grapefruit Capital. Families are often drawn here for a bit more space without leaving the metro.',
      sections: [
        { h: 'Cost of living', b: 'Prices range widely between older central neighborhoods and the newer areas out west. What your budget buys in Mission can differ noticeably from McAllen just next door \u2014 worth comparing side by side.' },
        { h: 'Schools', b: 'The area is served by Mission CISD and Sharyland ISD, and boundaries matter block to block. Tell us what needs to be close and we\u2019ll help you weigh school zones against commute and neighborhood.' },
        { h: 'Property taxes', b: 'With no state income tax in Texas, property taxes carry more of the load. Rates vary by district and exemptions matter \u2014 we\u2019ll walk you through what to expect for a specific home.' },
        { h: 'Lifestyle', b: 'Expect a quieter, more residential feel than central McAllen, with parks, birding at Bentsen-Rio Grande, and quick access back into the metro. Ten miles in the Valley can change the whole fit.' },
      ],
      picks: [
        { category: 'Eat-upscale', place: 'Loretto Bistro', pickedBy: 'Pam' },
        { category: 'Fitness', place: 'Point Padel Club', pickedBy: 'Mau' },
        { category: 'Pool service', place: 'Jeremy Hiller Pools', why: 'Hands down, best pool service we\'ve worked with!', pickedBy: 'Mau & Pam' },
      ],
    },
    es: {
      name: 'Mission', metaTitle: 'Vivir en Mission, TX \u2014 guía local de bienes raíces',
      metaDesc: 'Cómo es vivir en Mission, Texas: zonas, costo de vida, escuelas, impuestos prediales y estilo de vida, de un equipo local del Valle.',
      intro: 'Justo al oeste de McAllen, Mission combina zonas ya establecidas con crecimiento nuevo y una fuerte herencia citrícola \u2014 se le conoce como la capital de la toronja. Muchas familias llegan buscando un poco más de espacio sin salir del área metropolitana.',
      sections: [
        { h: 'Costo de vida', b: 'Los precios varían bastante entre las zonas céntricas más antiguas y las áreas nuevas del oeste. Lo que tu presupuesto compra en Mission puede ser distinto a McAllen, que está a un lado \u2014 conviene comparar.' },
        { h: 'Escuelas', b: 'La zona la atienden Mission CISD y Sharyland ISD, y los límites cambian de cuadra en cuadra. Dinos qué necesita quedar cerca y te ayudamos a pesar las escuelas junto con el traslado y la zona.' },
        { h: 'Impuestos prediales', b: 'Como Texas no tiene impuesto estatal sobre la renta, el predial pesa más. Las tasas cambian por distrito y las exenciones importan \u2014 te explicamos qué esperar para cada casa.' },
        { h: 'Estilo de vida', b: 'Un ambiente más residencial y tranquilo que el centro de McAllen, con parques, observación de aves en Bentsen-Rio Grande y acceso rápido de regreso al metro. Diez millas en el Valle cambian todo.' },
      ],
    },
  },

  pharr: {
    en: {
      name: 'Pharr', metaTitle: 'Living in Pharr, TX — a local real estate guide',
      metaDesc: 'What it\u2019s like to live in Pharr, Texas: neighborhoods, cost of living, schools, property taxes and lifestyle, from a local RGV real estate team.',
      intro: 'Directly south and east of McAllen, Pharr is a central, practical place to land \u2014 home to one of the Valley\u2019s busiest international bridges and a lot of everyday value for the money.',
      sections: [
        { h: 'Cost of living', b: 'Pharr often offers more affordable options than central McAllen while keeping you close to everything. We\u2019ll compare real listings so you can see the trade-offs for your budget.' },
        { h: 'Schools', b: 'The area is anchored by Pharr-San Juan-Alamo ISD (PSJA). Zones shift by neighborhood, so it\u2019s worth confirming for any specific address.' },
        { h: 'Property taxes', b: 'As across Texas, no state income tax pushes more onto property taxes; rates vary by district and exemptions matter. We\u2019ll clarify what to expect for a given home.' },
        { h: 'Lifestyle', b: 'A hardworking, well-connected city with strong cross-border commerce and quick access to the rest of the metro. What sells in McAllen isn\u2019t automatically what sells in Pharr \u2014 local nuance matters.' },
      ],
      picks: [
        { category: 'Pool service', place: 'Jeremy Hiller Pools', why: 'Hands down, best pool service we\'ve worked with!', pickedBy: 'Mau & Pam' },
      ],
    },
    es: {
      name: 'Pharr', metaTitle: 'Vivir en Pharr, TX \u2014 guía local de bienes raíces',
      metaDesc: 'Cómo es vivir en Pharr, Texas: zonas, costo de vida, escuelas, impuestos prediales y estilo de vida, de un equipo local del Valle.',
      intro: 'Justo al sur y al este de McAllen, Pharr es un punto central y práctico para establecerse \u2014 hogar de uno de los puentes internacionales más activos del Valle y con mucho valor por tu dinero.',
      sections: [
        { h: 'Costo de vida', b: 'Pharr suele ofrecer opciones más accesibles que el centro de McAllen sin alejarte de todo. Comparamos propiedades reales para que veas las concesiones según tu presupuesto.' },
        { h: 'Escuelas', b: 'La zona la ancla Pharr-San Juan-Alamo ISD (PSJA). Los límites cambian por colonia, así que conviene confirmarlo para cada dirección.' },
        { h: 'Impuestos prediales', b: 'Como en todo Texas, sin impuesto estatal el predial pesa más; las tasas cambian por distrito y las exenciones importan. Te aclaramos qué esperar para cada casa.' },
        { h: 'Estilo de vida', b: 'Una ciudad trabajadora y bien conectada, con fuerte comercio fronterizo y acceso rápido al resto del metro. Lo que se vende en McAllen no es automáticamente lo que se vende en Pharr \u2014 el matiz local importa.' },
      ],
    },
  },

  weslaco: {
    en: {
      name: 'Weslaco', metaTitle: 'Living in Weslaco, TX — a local real estate guide',
      metaDesc: 'What it\u2019s like to live in Weslaco, Texas: neighborhoods, cost of living, schools, property taxes and lifestyle, from a local RGV real estate team.',
      intro: 'Sitting mid-Valley between McAllen and Harlingen, Weslaco pairs agricultural roots with a wave of newer development \u2014 a convenient, steadily growing midpoint.',
      sections: [
        { h: 'Cost of living', b: 'Newer construction and available land can mean more square footage for the money than the central metro. We\u2019ll put options side by side so the trade-offs are clear.' },
        { h: 'Schools', b: 'Weslaco ISD anchors the city. Growth areas can bring new schools and shifting boundaries, so it\u2019s worth checking for any specific address.' },
        { h: 'Property taxes', b: 'No state income tax means property taxes carry more of the load; newer developments can carry additional district assessments worth understanding before you buy.' },
        { h: 'Lifestyle', b: 'A calmer pace with a central location, medical services, and easy reach to both ends of the Valley. Great for buyers who want space without feeling remote.' },
      ],
      picks: [
        { category: 'Eat-casual', place: 'Felice', why: 'Best pizza in the valley, hands down!', pickedBy: 'Mau' },
        { category: 'Eat-casual', place: 'Gonzalez Burgers', pickedBy: 'Mau' },
        { category: 'Movie theatre', place: 'WESMER Drive-In', pickedBy: 'Mau' },
      ],
    },
    es: {
      name: 'Weslaco', metaTitle: 'Vivir en Weslaco, TX \u2014 guía local de bienes raíces',
      metaDesc: 'Cómo es vivir en Weslaco, Texas: zonas, costo de vida, escuelas, impuestos prediales y estilo de vida, de un equipo local del Valle.',
      intro: 'En el centro del Valle, entre McAllen y Harlingen, Weslaco combina raíces agrícolas con una ola de desarrollo nuevo \u2014 un punto medio cómodo y en constante crecimiento.',
      sections: [
        { h: 'Costo de vida', b: 'La construcción nueva y el terreno disponible pueden darte más metros por tu dinero que el metro central. Ponemos las opciones lado a lado para que las concesiones queden claras.' },
        { h: 'Escuelas', b: 'Weslaco ISD ancla la ciudad. Las zonas de crecimiento pueden traer escuelas nuevas y límites que cambian, así que conviene revisarlo para cada dirección.' },
        { h: 'Impuestos prediales', b: 'Sin impuesto estatal, el predial pesa más; los desarrollos nuevos pueden traer cuotas de distrito adicionales que vale la pena entender antes de comprar.' },
        { h: 'Estilo de vida', b: 'Un ritmo más tranquilo con ubicación central, servicios médicos y acceso fácil a ambos extremos del Valle. Ideal para quien busca espacio sin sentirse lejos.' },
      ],
    },
  },

  mercedes: {
    en: {
      name: 'Mercedes', metaTitle: 'Living in Mercedes, TX — a local real estate guide',
      metaDesc: 'What it\u2019s like to live in Mercedes, Texas: neighborhoods, cost of living, schools, property taxes and lifestyle, from a local RGV real estate team.',
      intro: 'Known as the "Queen City of the Rio Grande Valley," Mercedes is a smaller, friendly town in the mid-Valley \u2014 home to the region\u2019s premium outlets and its long-running livestock show.',
      sections: [
        { h: 'Cost of living', b: 'Mercedes tends toward the more affordable end of the mid-Valley, which appeals to first-time buyers and anyone wanting more home for the budget. We\u2019ll compare what\u2019s realistic here.' },
        { h: 'Schools', b: 'The city is anchored by Mercedes ISD, with zones varying by neighborhood \u2014 worth confirming for a specific address.' },
        { h: 'Property taxes', b: 'No state income tax means property taxes carry more weight; rates vary by district and exemptions matter. We\u2019ll explain what to expect for a given home.' },
        { h: 'Lifestyle', b: 'A small-town feel with shopping at the outlets, community events, and a central location for reaching the rest of the Valley.' },
      ],
      picks: [
        { category: 'Movie theatre', place: 'WESMER Drive-In', pickedBy: 'Mau' },
        { category: 'Shopping', place: 'Mercedes Premium Outlets', pickedBy: 'Pam' },
      ],
    },
    es: {
      name: 'Mercedes', metaTitle: 'Vivir en Mercedes, TX \u2014 guía local de bienes raíces',
      metaDesc: 'Cómo es vivir en Mercedes, Texas: zonas, costo de vida, escuelas, impuestos prediales y estilo de vida, de un equipo local del Valle.',
      intro: 'Conocida como la "Ciudad Reina del Valle," Mercedes es un pueblo más pequeño y acogedor en el centro del Valle \u2014 hogar de los outlets premium de la región y de su tradicional feria ganadera.',
      sections: [
        { h: 'Costo de vida', b: 'Mercedes tiende al lado más accesible del centro del Valle, lo que atrae a compradores primerizos y a quien busca más casa por su presupuesto. Comparamos qué es realista aquí.' },
        { h: 'Escuelas', b: 'La ciudad la ancla Mercedes ISD, con zonas que varían por colonia \u2014 conviene confirmarlo para cada dirección.' },
        { h: 'Impuestos prediales', b: 'Sin impuesto estatal, el predial pesa más; las tasas cambian por distrito y las exenciones importan. Te explicamos qué esperar para cada casa.' },
        { h: 'Estilo de vida', b: 'Ambiente de pueblo pequeño con compras en los outlets, eventos comunitarios y una ubicación central para llegar al resto del Valle.' },
      ],
    },
  },

  harlingen: {
    en: {
      name: 'Harlingen', metaTitle: 'Living in Harlingen, TX — a local real estate guide',
      metaDesc: 'What it\u2019s like to live in Harlingen, Texas: neighborhoods, cost of living, schools, property taxes and lifestyle, from a local RGV real estate team.',
      intro: 'The hub of the eastern Valley, Harlingen is an established city with its own airport, a strong medical sector, and an easy gateway toward South Padre Island.',
      sections: [
        { h: 'Cost of living', b: 'Harlingen offers a range from established central neighborhoods to newer development, often at competitive value. We\u2019ll compare real options for your budget.' },
        { h: 'Schools', b: 'The city is anchored by Harlingen CISD, with zones varying by neighborhood \u2014 worth confirming for a specific address.' },
        { h: 'Property taxes', b: 'No state income tax means property taxes carry more of the load; rates vary by district and exemptions matter. We\u2019ll walk you through what to expect.' },
        { h: 'Lifestyle', b: 'A mature city with medical and air-travel access, parks along the Arroyo Colorado, and a quick drive to the coast. A strong fit for buyers who want amenities and an established feel.' },
      ],
      picks: [
        { category: 'Eat-casual', place: 'Ceviche Ceviche', pickedBy: 'Pam' },
        { category: 'Health', place: 'Integrative Rheumatology of STX', pickedBy: 'Pam' },
      ],
    },
    es: {
      name: 'Harlingen', metaTitle: 'Vivir en Harlingen, TX \u2014 guía local de bienes raíces',
      metaDesc: 'Cómo es vivir en Harlingen, Texas: zonas, costo de vida, escuelas, impuestos prediales y estilo de vida, de un equipo local del Valle.',
      intro: 'El centro del Valle oriental, Harlingen es una ciudad establecida con aeropuerto propio, un fuerte sector médico y una entrada fácil hacia South Padre Island.',
      sections: [
        { h: 'Costo de vida', b: 'Harlingen ofrece desde zonas céntricas ya establecidas hasta desarrollo nuevo, a menudo con buen valor. Comparamos opciones reales para tu presupuesto.' },
        { h: 'Escuelas', b: 'La ciudad la ancla Harlingen CISD, con zonas que varían por colonia \u2014 conviene confirmarlo para cada dirección.' },
        { h: 'Impuestos prediales', b: 'Sin impuesto estatal, el predial pesa más; las tasas cambian por distrito y las exenciones importan. Te explicamos qué esperar.' },
        { h: 'Estilo de vida', b: 'Una ciudad madura con acceso médico y aéreo, parques a lo largo del Arroyo Colorado y la costa a un paso. Buena opción para quien busca servicios y un ambiente establecido.' },
      ],
    },
  },

  'san-benito': {
    en: {
      name: 'San Benito', metaTitle: 'Living in San Benito, TX — a local real estate guide',
      metaDesc: 'What it\u2019s like to live in San Benito, Texas: neighborhoods, cost of living, schools, property taxes and lifestyle, from a local RGV real estate team.',
      intro: 'Between Harlingen and Brownsville, San Benito is a small, character-rich city known for its resacas \u2014 the winding oxbow waterways that give it the nickname "Resaca City" \u2014 and deep roots in Valley music.',
      sections: [
        { h: 'Cost of living', b: 'San Benito generally sits at an approachable price point in the lower Valley, appealing to first-time buyers and those wanting more space. We\u2019ll compare what\u2019s realistic here.' },
        { h: 'Schools', b: 'The city is anchored by San Benito CISD, with zones varying by neighborhood \u2014 worth confirming for a specific address.' },
        { h: 'Property taxes', b: 'No state income tax means property taxes carry more of the load; rates vary by district and exemptions matter. We\u2019ll explain what to expect for a given home.' },
        { h: 'Lifestyle', b: 'A close-knit, small-town feel with the resacas, local culture and music heritage, and an easy reach to both Harlingen and Brownsville.' },
      ],
    },
    es: {
      name: 'San Benito', metaTitle: 'Vivir en San Benito, TX \u2014 guía local de bienes raíces',
      metaDesc: 'Cómo es vivir en San Benito, Texas: zonas, costo de vida, escuelas, impuestos prediales y estilo de vida, de un equipo local del Valle.',
      intro: 'Entre Harlingen y Brownsville, San Benito es una ciudad pequeña y con carácter, conocida por sus resacas \u2014 los cuerpos de agua sinuosos que le dan el apodo de "Resaca City" \u2014 y por sus raíces profundas en la música del Valle.',
      sections: [
        { h: 'Costo de vida', b: 'San Benito suele ubicarse en un precio accesible del Valle bajo, atractivo para compradores primerizos y para quien busca más espacio. Comparamos qué es realista aquí.' },
        { h: 'Escuelas', b: 'La ciudad la ancla San Benito CISD, con zonas que varían por colonia \u2014 conviene confirmarlo para cada dirección.' },
        { h: 'Impuestos prediales', b: 'Sin impuesto estatal, el predial pesa más; las tasas cambian por distrito y las exenciones importan. Te explicamos qué esperar para cada casa.' },
        { h: 'Estilo de vida', b: 'Un ambiente de pueblo unido, con las resacas, la cultura local y la herencia musical, y acceso fácil tanto a Harlingen como a Brownsville.' },
      ],
    },
  },

  brownsville: {
    en: {
      name: 'Brownsville', metaTitle: 'Living in Brownsville, TX — a local real estate guide',
      metaDesc: 'What it\u2019s like to live in Brownsville, Texas: neighborhoods, cost of living, schools, property taxes and lifestyle, from a local RGV real estate team.',
      intro: 'The southernmost city in Texas and the seat of Cameron County, Brownsville pairs deep history and a major university with a wave of new energy \u2014 including the SpaceX activity out at Boca Chica and a growing coastal-adjacent economy.',
      sections: [
        { h: 'Cost of living', b: 'Brownsville spans historic central neighborhoods to newer growth on the edges, with a wide range of price points. We\u2019ll compare real options for your budget and goals.' },
        { h: 'Schools', b: 'The city is anchored by Brownsville ISD and is home to UTRGV and Texas Southmost College. Zones vary by neighborhood \u2014 worth confirming for a specific address.' },
        { h: 'Property taxes', b: 'No state income tax means property taxes carry more of the load; rates vary by district and exemptions matter. We\u2019ll clarify what to expect for a given home.' },
        { h: 'Lifestyle', b: 'A historic, culturally rich border city with birding and ecotourism, a working port, and fast-growing interest tied to nearby space and coastal development. Local context matters here more than most.' },
      ],
      picks: [
        { category: 'Eat-casual', place: 'La Villa Taqueria', why: 'Some of the best tacos in the valley, don\'t skip on the ice cream for dessert', pickedBy: 'Mau' },
        { category: 'Eat-upscale', place: 'Chilmoli', pickedBy: 'Mau' },
        { category: 'Zoo', place: 'Gladys Porter Zoo', pickedBy: 'Mau' },
        { category: 'Playhouse / family', place: 'Children\'s Museum of Brownsville', pickedBy: 'Pam' },
        { category: 'Eat-upscale', place: 'Jolie Petite', pickedBy: 'Pam' },
      ],
    },
    es: {
      name: 'Brownsville', metaTitle: 'Vivir en Brownsville, TX \u2014 guía local de bienes raíces',
      metaDesc: 'Cómo es vivir en Brownsville, Texas: zonas, costo de vida, escuelas, impuestos prediales y estilo de vida, de un equipo local del Valle.',
      intro: 'La ciudad más al sur de Texas y cabecera del condado de Cameron, Brownsville combina historia profunda y una universidad importante con una ola de energía nueva \u2014 incluida la actividad de SpaceX en Boca Chica y una economía cercana a la costa en crecimiento.',
      sections: [
        { h: 'Costo de vida', b: 'Brownsville abarca desde zonas céntricas históricas hasta crecimiento nuevo en las orillas, con una amplia gama de precios. Comparamos opciones reales según tu presupuesto y tus metas.' },
        { h: 'Escuelas', b: 'La ciudad la ancla Brownsville ISD y es sede de UTRGV y Texas Southmost College. Las zonas varían por colonia \u2014 conviene confirmarlo para cada dirección.' },
        { h: 'Impuestos prediales', b: 'Sin impuesto estatal, el predial pesa más; las tasas cambian por distrito y las exenciones importan. Te aclaramos qué esperar para cada casa.' },
        { h: 'Estilo de vida', b: 'Una ciudad fronteriza histórica y rica en cultura, con observación de aves y ecoturismo, un puerto activo y un interés creciente ligado al desarrollo espacial y costero cercano. Aquí el contexto local importa más que en otros lados.' },
      ],
    },
  },

  'south-padre-island': {
    en: {
      name: 'South Padre Island', metaTitle: 'Buying on South Padre Island, TX — a local guide',
      metaDesc: 'What to know about real estate on South Padre Island, Texas: the vacation and second-home market, costs, and lifestyle, from a local RGV team.',
      intro: 'South Padre Island is a different market from the mainland \u2014 a Gulf-front barrier island where much of the real estate is vacation homes, condos, and investment/rental property rather than primary residences.',
      sections: [
        { h: 'The market', b: 'Expect beachfront and bayfront condos and homes, with pricing and price-per-square-foot that run higher than the mainland. Many buyers are here for a second home or a rental investment \u2014 the underwriting is different, and we\u2019ll walk it through.' },
        { h: 'Costs to weigh', b: 'Beyond price, factor in HOA/condo fees, insurance (including wind and flood on a barrier island), and how seasonal rental demand affects returns. We\u2019ll help you look at the full picture.' },
        { h: 'Property taxes', b: 'No state income tax means property taxes carry more of the load; a second home doesn\u2019t receive a homestead exemption the way a primary residence can, which is worth planning for.' },
        { h: 'Lifestyle', b: 'Gulf beaches, fishing and watersports, dolphin and sea-turtle ecotourism, and a rhythm that shifts with winter Texans, spring, and summer. Point Isabel ISD serves the island and Port Isabel for year-round residents.' },
      ],
      picks: [
        { category: 'Eat-upscale', place: 'Viva SPI', pickedBy: 'Mau' },
        { category: 'Eat-upscale', place: 'Captain\'s Cove Oyster Bar', pickedBy: 'Pam' },
        { category: 'Eat-casual', place: 'Joe\'s Oyster Bar', why: 'Nothing like picking up an order of fried shrimp and taking it to the beach!', pickedBy: 'Mau' },
      ],
    },
    es: {
      name: 'South Padre Island', metaTitle: 'Comprar en South Padre Island, TX \u2014 guía local',
      metaDesc: 'Lo que debes saber sobre bienes raíces en South Padre Island, Texas: el mercado de casa de descanso e inversión, costos y estilo de vida, de un equipo local del Valle.',
      intro: 'South Padre Island es un mercado distinto al continente \u2014 una isla de barrera frente al Golfo donde gran parte de las propiedades son casas de descanso, condominios y propiedad de inversión o renta, más que residencia principal.',
      sections: [
        { h: 'El mercado', b: 'Encontrarás condominios y casas frente al mar y a la bahía, con precios y precio por metro más altos que en el continente. Muchos compran una segunda casa o una inversión de renta \u2014 el análisis es diferente y te lo explicamos paso a paso.' },
        { h: 'Costos a considerar', b: 'Además del precio, considera cuotas de HOA/condominio, seguros (incluyendo viento e inundación en una isla de barrera) y cómo la demanda de renta por temporada afecta el rendimiento. Te ayudamos a ver el panorama completo.' },
        { h: 'Impuestos prediales', b: 'Sin impuesto estatal, el predial pesa más; una segunda casa no recibe la exención de homestead como sí puede una residencia principal, algo que conviene planear.' },
        { h: 'Estilo de vida', b: 'Playas del Golfo, pesca y deportes acuáticos, ecoturismo de delfines y tortugas marinas, y un ritmo que cambia con los winter Texans, la primavera y el verano. Point Isabel ISD atiende la isla y Port Isabel para residentes de todo el año.' },
      ],
    },
  },
};

export const citySlugs = Object.keys(cities);

export const reviewsMeta = {
  en: {
    metaTitle: 'Client reviews — The Arper Group, RGV',
    metaDesc: '5.0 stars across 21 Google reviews. Real clients on working with Mauricio and Pamela across the Rio Grande Valley.',
    title: 'What clients say',
    ratingLine: '5.0 \u2605 \u00b7 21 Google reviews across our two profiles',
    lede: 'Every review below is a real Google review from a client we\u2019ve worked with across the Valley.',
    withMau: 'Worked with Mauricio',
    withPam: 'Worked with Pamela',
    verified: 'Google review',
  },
  es: {
    metaTitle: 'Reseñas de clientes — The Arper Group, Valle',
    metaDesc: '5.0 estrellas en 21 reseñas de Google. Clientes reales sobre trabajar con Mauricio y Pamela en todo el Valle.',
    title: 'Lo que dicen nuestros clientes',
    ratingLine: '5.0 \u2605 \u00b7 21 reseñas de Google entre nuestros dos perfiles',
    lede: 'Cada reseña aquí es una reseña real de Google de un cliente con quien trabajamos en el Valle.',
    withMau: 'Trabajó con Mauricio',
    withPam: 'Trabajó con Pamela',
    verified: 'Reseña de Google',
  },
};

// Curated real Google reviews. Spanish reviews stay in Spanish on both language pages.
export const reviews = [
  { author: 'Cesar Gonzalez', who: 'mau', lang: 'en', text: 'Hands down the best real estate experience we\u2019ve ever had \u2014 and Mauricio wasn\u2019t even in our city (San Antonio)! From start to finish, exceptional service, fast response times, and deep knowledge of the home buying process. We\u2019ve worked with several agents, but none have come close. He\u2019s in a league of his own.' },
  { author: 'Angela Salazar', who: 'mau', lang: 'en', role: 'Lender', text: 'As a lender, I\u2019ve worked with many real estate professionals, but Mauricio consistently stands out as one of the best. His responsiveness is top-tier, and his negotiation skills are a true asset to our mutual clients. If you want a Realtor who\u2019s responsive, knowledgeable, and genuinely committed to doing right by clients, Mauricio is the one you want by your side.' },
  { author: 'Tania Longoria', who: 'mau', lang: 'en', text: 'I met Mauricio by chance at an open house, feeling discouraged after another realtor made the process feel overwhelming. From the beginning he made me feel heard \u2014 no pressure, no sugar-coating, just honest guidance and genuine care. In the end he got me a great deal on my brand new house. A great realtor and a great human.' },
  { author: 'Guillermo Vela', who: 'mau', lang: 'en', text: 'Working with Mauricio was an amazing experience. He guided us through every step and made buying our fourplex investment feel smooth and stress free. Thanks to him, we accomplished our dream of investing in real estate. His knowledge, patience, and dedication truly made a difference.' },
  { author: 'Den Pastrana', who: 'mau', lang: 'es', text: 'Trabajar con Mauricio fue una experiencia increíble. Desde el primer día fue súper paciente y nos ayudó a encontrar exactamente lo que necesitábamos. Además, nos ayudó a negociar y bajar más de $10K del precio de la casa. Siempre amable, nos guió paso a paso hasta conseguir la casa de nuestros sueños. ¡Lo recomendamos ampliamente!' },
  { author: 'Martha Laura Rodriguez', who: 'mau', lang: 'es', text: 'Quiero agradecer profundamente a mi realtor Mauricio por su excelente trabajo. Siempre estuvo disponible, fue muy profesional y nos guió en cada paso del proceso. Gracias a su dedicación, todo fue mucho más fácil y tranquilo. ¡Totalmente recomendado!' },
  { author: 'Alex Hope', who: 'pam', lang: 'en', text: 'Pamela is a great realtor. She really cares about her customers\u2019 needs and devotes all her heart to helping them. She is my best realtor and surely one of the top realtors in the valley. She always sells!' },
  { author: 'Gestel DeAsis', who: 'pam', lang: 'en', text: 'We love working with Pamela! We\u2019re repeat clients who will always go back because she makes every transaction run smoothly. Always clear on communication, detail oriented, and I can always count on her being on our side. She advocates for her clients fiercely with their best interests at heart.' },
  { author: 'Paola Alaniz', who: 'pam', lang: 'en', text: 'I\u2019ve been working with Pamela for about two years. Although this was our first time purchasing a home, we never felt lost \u2014 she provided all the information to make the process smooth and easy, and seems to have connections everywhere. She doesn\u2019t offer a sales agreement she wouldn\u2019t feel comfortable signing herself, and for that, she is truly great.' },
  { author: 'Diana Othon', who: 'pam', lang: 'en', text: 'Pamela helped me find my new home and I couldn\u2019t be happier. Deep market knowledge, attention to detail, and a genuine commitment to understanding my needs made the entire journey smooth and stress-free. She truly went above and beyond \u2014 she is simply the best!' },
  { author: 'Bernardo Somohano', who: 'pam', lang: 'en', text: 'I had the pleasure of working with Pamela Perez and cannot speak highly enough of the experience. Her professionalism and dedication to finding the ideal home were evident \u2014 always available, proactive, and making sure I felt comfortable and informed every step of the way.' },
];
